# Check gen/ directory generatable using the modified contents
name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-lastest
    name: TEST
    steps:
      - uses: actions/checkout@v2
      
      - name: Toast
        run: |
          cd idl
          ./build.sh