name: PushToTestRepository

on:
  pull_request:
    branches:
      - main

jobs:
  push-to-test-repository:
    runs-on: ubuntu-latest
    name: Push to test repository
    steps:
      - uses: actions/checkout@v2

      - name: Getting Commit Hash
        shell: bash
        run: |
          githash=$(git rev-parse --short "$GITHUB_SHA")
          echo "githash=$githash" >> $GITHUB_ENV

      - name: Git Clone - Test Repository
        run: |          
          git clone https://github.com/zbeeS2/test.git

      - name: Generate Test File
        run: |
          cd test
          touch test.file
          echo "this is test" >> test.file

      - name: git push test.file
        run: |
          git add test.file
          git commit -m "add test.file with ${{ env.githash }}"
          git push origin