# 1. 태그 정보 가져오기 git tag --sort=-v:refname | head -1
# 2. 태깅 하기

name: Release Tag
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract Recent Version
      run: |
        # RECENT_TAG=$(git tag --sort=-v:refname | head -1)
        RECENT_TAG="v0.0.1"
        TAG_ARR=$(echo $RECENT_TAG | tr "." "\n")
        LAST_TAG_NUM=$(expr TAG_ARR[-1] + 1)
        NEW_TAG_NAME="$TAG_ARR[0].$TAG_ARR[1].$LAST_TAG_NUM"
        echo "NEW_TAG_NAME=$NEW_TAG_NAME" >> $GITHUB_ENV

    - name: test
      run: echo ${{env.NEW_TAG_NAME}}
    # - name: Create Release
    #   uses: actions/create-release@v1
    #   env: 
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with: 
    #     tag_name: ${{ env.recent_tag }} 
    #     release_name: "What is this?"
    #     body: |
    #       Changes in this Release
    #       - First Change
    #       - Second Change
    #     draft: false
    #     prerelease: false